events {}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        location /app1 {
            set $app1_upstream app1:5001;
            proxy_pass http://$app1_upstream/;
        }

        location /app2 {
            set $app2_upstream app2:5002;
            proxy_pass http://$app2_upstream/;
        }
    }
}
