name: CI

on:
 push:
   branches:
     - main

 pull_request:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker compose build

      - name: Start Services
        run: docker compose up -d

      - name: Wait for services to be healthy
        run: |
          for i in {1..30}; do
            app1_status=$(docker inspect app1 --format '{{.State.Health.Status}}')
            app2_status=$(docker inspect app2 --format '{{.State.Health.Status}}')

            if [ "$app1_status" = "healthy" ] && [ "$app2_status" = "healthy" ]; then
               echo "Both services are healthy"
               exit 0
            fi

            echo "Waiting for services..."
            sleep 2
          done

          echo "Services did not become healthy"
          docker compose ps
          exit 1

      - name: Test App 1
        run: curl http://localhost:8080/app1/ | grep "App 1 - Running behind Nginx!"

      - name: Test App 2
        run: curl http://localhost:8080/app2/ | grep "App 2 - Running behind Nginx!"

      - name: Push images to GHCR
        run: |
          docker push ghcr.io/chinmay03droid/nginx-reverse-proxy-app1:latest
          docker push ghcr.io/chinmay03droid/nginx-reverse-proxy-app2:latest

